### ISSUE TITLE
Failed to build vendored Boolector

### ISSUE THREAD

**Issue by cdisselkoen** [fatemender/boolector-sys#13]
I tried to follow the instructions in the new README to make a crate that depended on `boolector-sys` with vendored Boolector.

Cargo.toml:
```toml
[dependencies]
boolector-sys = { version = "0.6", features = ["vendor-lgl"] }
```

This failed to build, with the error:
```
error: failed to run custom build command for `boolector-sys v0.6.0`

Caused by:
  process didn't exit successfully: `/home/craig/blah/target/debug/build/boolector-sys-1460bc80a8064f48/build-script-build` (exit code: 101)
  --- stdout
  running "./contrib/setup-lingeling.sh"

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', /home/craig/.cargo/registry/src/github.com-1ecc6299db9ec823/boolector-sys-0.6.0/build-vendor.rs:93:39
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This is on Ubuntu 20.04, with `build-essential`, `cmake`, and `curl` all installed.  Anecdotally I got the same error on Arch Linux.

Am I doing something wrong?  Is this a bug?

**Comment by fatemender** [comment]
Looks like a bug, probably something to do with execute permission removed by Cargo, I'll have a look tomorrow, thanks.

**Comment by ChristianMoesl** [comment]
@cdisselkoen I tried to analyse/fix the permissions problem. But to me it looks like, this got fixed in [007bc0e
](https://github.com/fatemender/boolector-sys/commit/007bc0e3b7ac76b8b4b3d13d92a7a4fca1baf97c). 

Can you confirm that? And if so, can you also bump your `boolector-sys` dependency version in your `boolector-rs` crate? We would like to publish our project on crates.io and we need the latest version of your crate for that 😄

**Comment by cdisselkoen** [comment]
Yes, it seems to be fixed, thanks!

I will certainly make a new release of `boolector-rs` shortly - I was waiting on resolution of this issue.

Thanks again!

**Comment by cdisselkoen** [comment]
One final note - the README lists tools required for the build, I believe Git is also required for a successful vendored build (it tries to clone some googletest repo).

**Comment by cdisselkoen** [comment]
`boolector` version 0.4.2 just released, and it has its own `vendor-lgl` feature which activates the corresponding feature of `boolector-sys`
