### ISSUE TITLE
No Boolector sources in 0.6.2 package 

### ISSUE THREAD

**Issue by ChristianMoesl** [fatemender/boolector-sys#15]
Hi,

first, thanks for pulling my fix in so fast. But I have a little problem with the published package v0.6.2.

In the [package v0.6.1](https://docs.rs/crate/boolector-sys/0.6.1/source/), the boolector sources of the submodule are included, whereas in [package v0.6.2](https://docs.rs/crate/boolector-sys/0.6.2/source/) these sources are missing. Therefore the build for v0.6.2 fails.

**Comment by fatemender** [comment]
Whoops, sorry about that.  Forgot one of the publishing steps.  Fixed in 0.6.3.
