### ISSUE TITLE
Cannot build on Windows

### ISSUE THREAD

**Issue by CatOnTheHorizon** [fatemender/boolector-sys#17]
Greetings, I intend to utilize this crate in my project, which operates on a Windows system. Upon adding it to the project's toml file, the compilation failed. It appears that the build-vendor.rs file lacks Windows compatibility considerations. How may I utilize this crate on a Windows system?

**Comment by fatemender** [comment]
Hi!

It's specifically mentioned on the `README` that vendored build is available only for UNIX-like platforms.  If you want to build under Windows, you'll need to build your own shared library (`boolector.dll`) first.  Upstream does not really support full-featured Windows builds as well, as outlined here: https://github.com/Boolector/boolector/blob/master/COMPILING_WINDOWS.md.  I was able to build a DLL using these steps but they are certainly not subject to cargo build script automation.

If and when you succeed in building the DLL (and the import library) in your Windows environment, put them under `target/debug` or `target/release` and build your application without `vendor-lgl` feature of the `boolector-sys` crate.

Alternatively, just build under WSL with `vendor-lgl` enabled.  This works.

Cheers!

**Comment by CatOnTheHorizon** [comment]
Thank you very much for your reply. I had earlier overlooked the description in the Readme. I will follow your advice and try it out. Thank you again.
